general:
    base_path: /home/jshaoaj/project/unlearning/benchmark_FU/scratch
clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 10 

    # The number of clients selected in each round
    per_round: 10

    # Should the clients compute test accuracy locally?
    do_test: true




server:
    address: 127.0.0.1
    port: 8020

data:
    # The training and testing dataset
    datasource: CIFAR10
    random_seed: 1234
    # Number of samples in each partition
    partition_size: 1000

    # IID or non-IID?
    sampler: distribution_noniid
    label_concentration: 0.5

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 40

    # The maximum number of clients running concurrently
    max_concurrency: 10

    # The target accuracy
    target_accuracy: 0.90

    # The machine learning model
    model_type: torch_hub
    model_name: resnet18

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 64
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    optimizer:
        lr: 0.01
        weight_decay: 0.0001
        momentum: 0.9
