clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 10 

    # The number of clients selected in each round
    per_round: 10

    # Should the clients compute test accuracy locally?
    do_test: true




server:
    address: 127.0.0.1
    port: 8080
    
    unlearn: true # unlearn removed clients
    retrain: true # unlearning with retraining
    removed_clients: [1, 2] # the clients that are unlearned
    

data:
    # The training and testing dataset
    datasource: CIFAR10
    random_seed: 1234
    # Number of samples in each partition
    partition_size: 1000

    # IID or non-IID?
    sampler: distribution_noniid
    label_concentration: 0.6

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 10

    # The maximum number of clients running concurrently
    max_concurrency: 10

    # The target accuracy
    target_accuracy: 0.90

    # The machine learning model
    model_type: torch_hub
    model_name: resnet18

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 64
    optimizer: SGD

    checkpoint_dir: "unlearn_checkpoints" # save the model after each round

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    optimizer:
        lr: 0.01
        weight_decay: 0.0001
